apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: yasirazam/cicd-potfolio:298d1cd9dbd6a33a83c20bc97bd0d04f1b705d7e
          ports:
            - containerPort: 80
