apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          # ðŸ‘‡ Replace <YOUR_DOCKERHUB_USERNAME> with your actual username
          image: yasirazam/cicd-potfolio:latest
          ports:
            - containerPort: 80
