apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
spec:
  type: NodePort       # good for Minikube + minikube service
  selector:
    app: portfolio-frontend
  ports:
    - port: 80         # service port
      targetPort: 80   # container port
      nodePort: 30080  # optional fixed NodePort (range 30000â€“32767)
